### PR TITLE
Bump CC

### PR DESCRIPTION
**Pull request by ghost**
This is a Bump CC for people who want to grow their Server. These codes are not standalone and need to be used together. I have specified everything as per the Contributing.md.

**Features:-**

1. Pings the role when its the time to bump

2. Easy to use and customize

3. A command that shows the Rank and LeaderBoard.

4. The Reaction CC, which helps to add and remove Bumping Roles.

5. An Interval CC that sends messages when the time has come to bump. (Mentioned above) Also, it strikes out the message in the channel after the bumping has been done.

### Code Status:-
The Codes are given in a 3 separate files, which are:-

1. Reaction CC:- Adds and Removes the roles when bumping is successful

2. An Interval CC:- Edits the Voice Channel name, along with sending the Bump Message

3. Regex CC:- This contains the code of `!d lb`, `!d bump` and `!d rank`. This also, strikes out the message sent by the Interval CC.

This is not the end of the list, and I'm planning to add more functionality.

Thanks

### CODE REVIEW

**Review by DZ-TM — COMMENTED** [review]
Will go back to this when I've got more time, mainly briefly went over it

**Comment by soudblox** [comment]
Leaderboard can get you banned from disboard, so I'm just gonna remove the lb code when I use it

**Comment by ghost** [comment]
Yeah, its just for people who wanna use it. I'll put a warning statement in the Leaderboards. Thanks

**Comment by DZ-TM** [comment]
Don't want to support Disboard in any way at meh github anymore

**Pull request closed without merging**
